### ISSUE TITLE
Quests don't show up on the chat

### ISSUE THREAD

**Issue by DannyIsYog** [Zrips/Jobs#236] opened 2018-09-05 22:26 UTC
Version 1.13.1

The quests don't show up on the player's chat, it appears like this:

![imagem](https://user-images.githubusercontent.com/43012385/45124591-d0099380-b162-11e8-9731-96a7b5834994.png)

Even tho you can clearly see it in the console (homemade server test):

![imagem](https://user-images.githubusercontent.com/43012385/45124637-f62f3380-b162-11e8-9bbb-6a3df7e330ec.png)

Code of the job (name and desc not in english sorry :/ ):
```
Lenhador:
    fullname: Lenhador
    shortname: L
    description: Ganha dinheiro a plantar e cortar árvores.
    ChatColour: GREEN
    chat-display: full
    max-level: 75
    leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
    income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01)
      * ((numjobs-1)*0.05))
    points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(joblevel-1)*0.01)
      * ((numjobs-1)*0.05))
    experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
    rejoinCooldown: 10
    Gui:
      Id: 17
      Data: 2
    Quests:
      '1':
        Name: Break Oak wood
        Action: Break
        Target: 17-0
        Amount: 300
        RewardCommands:
        - money give [playerName] 500
        - msg [playerName] Completed quest!
        RewardDesc:
        - Break 300 Oak wood
        - Get 500 bucks for this
        Chance: 40
        toLevel: 3
        fromLevel: 5
      '2':
        Name: Zombie killer
        Action: Kill
        Target: Zombie
        Amount: 50
        RewardCommands:
        - money give [playerName] 2000
        - msg [playerName] Completed quest!
        RewardDesc:
        - Kill 50 zombies
        - Get 2000 for this!
      '3':
        Name: Chicken cooker
        Action: Smelt
        Target: COOKED_CHICKEN
        Amount: 20
        RewardCommands:
        - money give [playerName] 300
        - msg [playerName] Completed quest!
        RewardDesc:
        - Cook some chicken breasts
        - Get 300 for this!
    Place:
      '6':
        income: 0.50
        points: 0
        experience: 0.20
      6-1:
        income: 0.50
        points: 0
        experience: 0.20
      6-2:
        income: 0.50
        points: 0
        experience: 0.20
      6-3:
        income: 0.50
        points: 0
        experience: 0.20
      6-4:
        income: 0.50
        points: 0
        experience: 0.20
      6-5:
        income: 0.50
        points: 0
        experience: 0.20
    Break:
      17-0:
        income: 0.90
        points: 0
        experience: 0.70
      17-1:
        income: 0.90
        points: 0
        experience: 0.70
      17-2:
        income: 0.90
        points: 0
        experience: 0.70
      17-3:
        income: 0.90
        points: 0
        experience: 0.70
      162-0:
        income: 0.90
        points: 0
        experience: 0.70
      162-1:
        income: 0.90
        points: 0
        experience: 0.70
      18-0:
        income: 0.40
        points: 0
        experience: 0.20
      18-1:
        income: 0.40
        points: 0
        experience: 0.20
      18-2:
        income: 0.40
        points: 0
        experience: 0.20
      18-3:
        income: 0.40
        points: 0
        experience: 0.20
      161-0:
        income: 0.40
        points: 0
        experience: 0.20
      161-1:
        income: 0.40
        points: 0
        experience: 0.20
```

**Comment by smmmadden** [comment] 2018-09-07 03:33
I can confirm the same behavior with PaperSpigot 1.13.1 (build 222) that the chat window is not provide quest details after issuing /jobs quests 
![image](https://user-images.githubusercontent.com/10309346/45196918-956c2d80-b22c-11e8-93fc-76e0748d17f1.png)
But on the server when the command was sent above, it paints a different message there.
![image](https://user-images.githubusercontent.com/10309346/45196939-b2a0fc00-b22c-11e8-8f5b-851924a0b82f.png)

**Comment by smmmadden** [comment] 2018-09-07 14:54
What's also interesting is that if you use jobs quests username in the server console, you can see (some - not all) of the quests for a job.  Doesn't matter if you try to add the job name after quests, the results are the same.  Only the first 3 quests in a job are shown and the two jobs I have that contain quests, there are 8 each.  Is it possible that quests should not be under Jobs and it is a separate entry (globally)?
![image](https://user-images.githubusercontent.com/10309346/45225957-b879fa00-b28b-11e8-9cf9-f422dd14cda3.png)

**Comment by smmmadden** [comment] 2018-09-07 15:54
Final test was to confirm the above where more than one job has Quests associated with it.  I tried with two of the 8 in the second job - plant 90 birch saplings and chop 100 birch logs.  Neither paid or acknowledged quest completion.  So either its a bug in not registering all quests for all jobs, quests are only supported in one job or quests should not be listed under any job as it is global. -Steve

**Comment by smmmadden** [comment] 2018-09-20 12:17
@Zrips - any update on this issue? Thanks, Steve

**Comment by montlikadani** [comment] 2018-10-06 18:06
Double messages may occur because the double message may be a Minecraft or Java problem. I did this (fixed) to restart my computer and this double message did not come up.
From the next version, the quest command will not be use in the console. Or at least JSON will be without the command.

**Comment by smmmadden** [comment] 2018-10-12 02:49
I've been trying to use /jobs quests in-game and the results are the same.  Look at Quests #2 - I've tried with double quoting, single quoting and without.  They all result in the same error on the console and no quests getting completed.
![image](https://user-images.githubusercontent.com/10309346/46845028-90f4e080-cda7-11e8-82ef-fbf250dbbfa2.png)
While the log shows /jobs quests was executed, this is just the server recording the in-game command.
[22:43:40] [Server thread/INFO]: smmmadden issued server command: /jobs quests
[22:43:40] [Server thread/INFO]: Expected whitespace to end one argument, but found trailing data
[22:43:40] [Server thread/INFO]: ...??????????????????????????????????????? Create Tree Farm 0/160","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Woodcutter
Flatten land 40x40x40x40 square area
Get $75 for this!
New quest in: 5 hours 16 min 19 sec "}]}}}]<--[HERE]
[22:43:40] [Server thread/INFO]: Expected whitespace to end one argument, but found trailing data
[22:43:40] [Server thread/INFO]: ...??????????????????????????????????????? Plant Birch Saplings 0/90","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Woodcutter
Plant 90 Birch saplings to fill the Tree Farm
Make sure there are at least 4 blocks between each sapling
Get $100 for this!
New quest in: 5 hours 16 min 19 sec "}]}}}]<--[HERE]
[22:43:40] [Server thread/INFO]: Expected whitespace to end one argument, but found trailing data
[22:43:40] [Server thread/INFO]: ...??????????????????????????????????????? Plant Oak Saplings 57/90","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"TreeFarmer
Plant 90 saplings to fill the Tree Farm
Make sure there are at least 4 blocks between each sapling
Get $100 for this!
New quest in: 5 hours 16 min 19 sec "}]}}}]<--[HERE]
[22:43:40] [Server thread/INFO]: Expected whitespace to end one argument, but found trailing data
[22:43:40] [Server thread/INFO]: ...??????????????????????????????????????? Create Tree Farm 0/160","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"TreeFarmer
Flatten land 40x40x40x40 square area
Get $75 for this!
New quest in: 5 hours 16 min 19 sec "}]}}}]<--[HERE]
[22:43:40] [Server thread/INFO]: Expected whitespace to end one argument, but found trailing data
[22:43:40] [Server thread/INFO]: ...??????????????????????????????????????? Plant Oak Saplings 57/90","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"TreeFarmer
Plant 90 saplings to fill the Tree Farm
Make sure there are at least 4 blocks between each sapling
Get $100 for this!
New quest in: 5 hours 16 min 19 sec "}]}}}]<--[HERE]

Configuration for the Woodcutter job with Quests.  Goes back to my thinking that should quests be for outside a job entirely or can a quests be included as an option for that job.
https://hastebin.com/gifiqugaka.php

**Comment by montlikadani** [comment] 2018-10-12 14:19
You need to use the DEV. builds from: https://github.com/Zrips/Jobs/releases

**Comment by smmmadden** [comment] 2018-10-12 16:48
confirmed, this is still an issue in the new 4.8.0 build added by Zrips today.

**Comment by smmmadden** [comment] 2018-10-13 16:37
latest dev build you made today.  I think I identified the issue with Quests.
1. **jobs quests smmmadden** in the console shows no quests but ******* smmmadden(0) ******* with no errors.  It should provide what quests a players has completed though.
2. **/jobs quests** in-game still shows the same as #1 
3. **/jobs quests** the same INFO lines thrown for DARK_OAK_LOG, ACACIA_LOG, OAK_SAPLING and GRASS_BLOCK as target values.  The others seem to pass validation or somehow being ignored.

Each of the errors thrown all point to the characters added before writing out the Quest Name where it looks like a color code is being inserted with **§e** and that is being marked as the issue for this statement or the line is too long or that the Job Name should end the double quote before adding the RewardDesc lines. 
[12:19:09] [Server thread/INFO]: Expected whitespace to end one argument, but found trailing data
[12:19:09] [Server thread/INFO]: ...????**§e**??????????????????????????????????? Create Tree Farm 0/160","hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"Woodcutter
Flatten land 40x40x40x40 square area
Get $75 for this
New quest in: 15 hours 40 min 50 sec "}]}}}]**<--[HERE]**

**Comment by montlikadani** [comment] 2018-10-13 16:52
I'll tell you the truth, it does not show me the quest either to anyone and I can not find the source of the bug (path).

**Comment by smmmadden** [comment] 2018-10-13 16:55
Just found the source code here:
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/commands/list/quests.java
https://github.com/Zrips/Jobs/blob/master/src/main/java/com/gamingmesh/jobs/container/QuestProgression.java

The second one (bottom) covers the server console request of jobs quests.

**Comment by montlikadani** [comment] 2018-10-13 17:11
I'm not a big coder (maybe I should not have started Minecraft plugin creation/development), I found some minor bugs and later fix and test it.

**Comment by Zrips** [comment] 2018-10-14 11:01
99f13e5c475750614385ac2a62d19a35a56aa4be

**Closed by Zrips** 2018-10-14 11:01 UTC
Labels: bug
