### ISSUE TITLE
Jobs db not 'transferring' data to game, and/or retaining all jobs info

### ISSUE THREAD

**Issue by Kayepur** [Zrips/Jobs#37] opened 2016-07-20 02:54 UTC
After updating to 1.9.4 from 1.8.8, I am getting complaints that 'my jobs are losing levels'. I have updated the plugin to vs. 3.5.1. I have tried using MySQL instead of SQLite, and have tried manually adding levels/xp/points either in-game, or through the MySQL itself. The issue appears to be this: the data is saved correctly in the database (sqlite was what we started with) but it fails to 'remember' ALL of the jobs' data when /jobs stats is run. It only lists up to three (limit is 3 jobs, default) jobs and their levels, and 99% the level is incorrect. I haven't seen any errors print to the console, so I'm not sure where to begin looking to get this resolved. It had been going on since the update to 1.9.4. 

Thanks!

**Comment by Codeloper** [comment] 2016-08-04 22:42
I have the same problem on a server network and I think the problem is produced by the players cache.
It stores data for ever (or up to next restart) and so wrong values are cached. This could be fixed by always reloading cache in PlayerJoinEvent.
But because of your horrible dependency management I couldn't do this on the quick.

**Comment by jackstrosahl** [comment] 2019-01-22 05:09
I have an issue on a MultiServer setup that points won't sync between servers right away, is this related?  And, is there significant work started on this, or could I do it in a pr?  Just let me know where to start, thanks!

**Closed** 2019-02-06 13:21 UTC
Labels: bug
