### ISSUE TITLE
Console Error (I've noticed it happens when the server/a plugin checks for an update)

### ISSUE THREAD

**Issue by BakProject** [Zrips/Jobs#387] opened 2019-03-18 16:53 UTC
I am looking at my console and I've noticed that there is an error popping up that says," 

> 18.03 10:31:43 [Server] ERROR A PluginData-source caused an exception: Jobs, you can disable the integration under 'Plugins.Jobs.Enabled'
> 18.03 10:31:43 [Server] WARN Error was caught by com.djrapitops.plan.utilities.html.structure.AnalysisPluginsTabContentCreator
> 18.03 10:31:43 [Server] INFO java.lang.NullPointerException: null
> 18.03 10:31:43 [Server] INFO at com.djrapitops.pluginbridge.plan.jobs.JobsData.getServerData(JobsData.java:68) ~[?:?]
> 18.03 10:31:43 [Server] INFO at com.djrapitops.plan.utilities.html.structure.AnalysisPluginsTabContentCreator.lambda$analyzeAdditionalPluginData$0(AnalysisPluginsTabContentCreator.java:148) ~[?:?]
> 18.03 10:31:43 [Server] INFO at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:291) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_121]
> 18.03 10:31:43 [Server] INFO at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_121]

I do not know what is causing this and do not know how to recreate it. There is somebody that posted this in a comment section for Jobs Reborn and thought I would bring the error here first.

**Comment by montlikadani** [comment] 2019-03-18 17:05
@Rsl1122 Plan seems to be unable to retrieve data from Jobs so throw this error. I confirm that this error has no path to Jobs.
@BakProject Have you tried to use the plugin without a Plan on a PaperSpigot server?

**Comment by BakProject** [comment] 2019-03-18 17:25
I am sorry. I actually have no idea what a PaperSpigot server is. Any way you could point me in the direction so I can try to fix this problem?

**Comment by montlikadani** [comment] 2019-03-18 17:27
Disable `Plugins.Jobs.Enabled` in the Plan configuration.

**Comment by BakProject** [comment] 2019-03-18 17:31
Would this be in the spigot.yml or server.properties?

**Comment by montlikadani** [comment] 2019-03-18 17:33
If you are using **Plan** software, you know.

**Comment by Rsl1122** [comment] 2019-03-18 18:30
Duplicate of #377 

I haven't tested the commit that mentioned that issue yet.

**Comment by BakProject** [comment] 2019-03-18 18:41
Oh the Plan Plugin. I'm sorry! I completely forgot that was even on the server, I kept thinking that it was some sort of different CraftBukkit or Spigot. I will give it a shot and let you know!

**Comment by BakProject** [comment] 2019-03-18 19:31
As far as I can see changing the plugin integration for 'Jobs' to false in the config.yml for the Plans Plugin has worked and I have not seen that error yet! Thanks for the help!

**Comment by BakProject** [comment] 2019-03-19 20:19
This change has fixed the console error (at least as far as I have seen)! Thank you so much for the help in removing that error message.

**Closed** 2019-05-02 13:34 UTC
Labels: duplicate
