### ISSUE TITLE
Karma plugin load a jobs class when karma trying to connect to a database.

### ISSUE THREAD

**Issue by Rosstail** [Zrips/Jobs#1418] opened 2022-03-14 16:54 UTC
Disclaimer: I am the developper of Karma (there's multiple plugin name like it but I send the link below), this bug happens on one of my plugin user server and I wasn't able to reproduce it on my own server.

It seems my plugin try to load a Jobs class when it comes to connect to the database, depite karma has nothing related to Jobs. Do you have an idea of how can I fix it ? Thanks in advance.

---

**ERROR:**
```
Error on startup
https://pastebin.com/TsuGneWs
```

**ERROR LOCATION**
```
//https://github.com/Rosstail/Karma/blob/master/src/main/java/com/rosstail/karma/datas/DBInteractions.java

private Connection openConnection() throws SQLException, ClassNotFoundException {
        Connection conn;
        synchronized (this) {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conn = getConnection("jdbc:mysql://" + host + ":" + port + "/" + database, username, password); // HERE
            return conn;
        }
    }
```

---

**Jobs version:** 5.0.2.1 MySQL

**Server Type (Spigot/Paper/etc):** Paper-238

**Server Version (using `/ver`):** 1.18.2

**Relevant plugins (Delete if this isn't needed):** [Karma 1.10.3](https://www.spigotmc.org/resources/karma.76077/)

**Comment by Zrips** [comment] 2022-05-26 13:16
Could not reproduce this issue with latest and 5.0.1.4 Jobs plugin version. So cant really identify and say what happen in that instance to cause error like that. If issue continues we can investigate more, but for time being closing ticket as there isint much to work on.

**Closed by Zrips** 2022-05-26 13:16 UTC
Labels: Bug Report
