### ISSUE TITLE
[1.16.5] - Problem with joining jobs.

### ISSUE THREAD

**Issue by Pukejoy** [Zrips/Jobs#1131] opened 2021-03-25 23:49 UTC
**Detailed description of the issue:**
Apparently the new version of Jobs has a bug which is the following. When a player joins a job, for example Miner and then attempt to join another job the plugin says that the player is already in this job. This affects every job except the one that you have joined first. Also it only shows the first joined job in the `/jobs stats` command.

- Have you edited the configs? No, I haven't edit them. Everything is default.

**Jobs version:** 4.17.1 (as of 26/03/2021 the latest)

**Server Type (Spigot/Paper/etc):** Paper, Build-567 (as of 26/03/2021 01:49 EEST, the latest)

**Server Version (using `/ver`):** This server is running Paper version git-Paper-567 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT)  | Previous version: git-Paper-566 (MC: 1.16.5)

**Java Version:** Java 11

**Startup Flags:** `java -Xms128M -Xmx4096M -Dterminal.jline=false -Dterminal.ansi=true -jar server.jar`

**Plugins List:** AuthMe, EconomyShopGUI, EssentialsX, EssentialsXChat, EssentialsXProtect, EssentialsXSpawn, HolographicDisplays, Jobs, LuckPerms, Residence, SkinsRestorer, SuperVanish, TAB, Vault WorldEdit, WorldGuard

I'm sorry if this Bug report doesn't have enough information. I have tried to include everything that I think is relevant to the issue. If needed, I can provide more information such as - logs or screenshots.

**Comment by Royalflamejlh** [comment] 2021-03-26 00:29
Duplicate of #1115

**Closed** 2021-03-26 00:37 UTC
Labels: Bug Report
