### ISSUE TITLE
Fisherman job not working

### ISSUE THREAD

**Issue by ClickErrorxD** [Zrips/Jobs#1759] opened 2024-05-16 15:36 UTC
***Detailed description of the issue:***
A player got to level 25 in fishing, and since then, no one else seems to be able to get exp or money from the fisherman job.
---
**CONFIG SECTION**
```
Fisherman:
  fullname: Fisherman
  shortname: Fi
  FullDescription:
  - "Earns money from fishing."
  ChatColour: AQUA
  chat-display: full
  max-level: 200
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  rejoinCooldown: 10
  maxDailyQuests: 2
  Quests:
    '1':
      Name: Fisherman - Easy
      Objectives:
      - Fish;cod;16
      RewardCommands:
      - eco give [playerName] 100
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a100'
    '2':
      Name: Fisherman - Easy
      Objectives:
      - Fish;salmon;16
      RewardCommands:
      - eco give [playerName] 150
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a150'
    '3':
      Name: Fisherman - Easy
      Objectives:
      - Fish;tropical_fish;16
      RewardCommands:
      - eco give [playerName] 175
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a175'
    '4':
      Name: Fisherman - Medium
      Objectives:
      - Fish;pufferfish;16
      RewardCommands:
      - eco give [playerName] 200
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a200'
    '5':
      Name: Fisherman - Medium
      Objectives:
      - Fish;cod;48
      RewardCommands:
      - eco give [playerName] 225
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a225'
    '6':
      Name: Fisherman - Medium
      Objectives:
      - Fish;salmon;32
      RewardCommands:
      - eco give [playerName] 250
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a250'
    '7':
      Name: Fisherman - Medium
      Objectives:
      - Fish;tropical_fish;32
      RewardCommands:
      - eco give [playerName] 275
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a275'
    '8':
      Name: Fisherman - Hard
      Objectives:
      - Fish;pufferfish;32
      RewardCommands:
      - eco give [playerName] 300
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a300'
    '9':
      Name: Fisherman - Hard
      Objectives:
      - Fish;cod;96
      RewardCommands:
      - eco give [playerName] 350
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a350'
    '10':
      Name: Fisherman - Hard
      Objectives:
      - Fish;salmon;64
      RewardCommands:
      - eco give [playerName] 375
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a375'
    '11':
      Name: Fisherman - Hard
      Objectives:
      - Fish;tropical_fish;64
      RewardCommands:
      - eco give [playerName] 375
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a375'
    '12':
      Name: Fisherman - Impossible
      Objectives:
      - Fish;pufferfish;64
      RewardCommands:
      - eco give [playerName] 400
      - mamsg [playerName] You have completed a job quest.
      RewardDesc:
      - '&9&l* &7Complete the following quest'
      - '&9&l* &7and you will get rewarded.'
      - ''
      - '&9Options:'
      - '&9&l* &7Reward: &a&l$&a400'
  commands:
    reeldealtag:
      command:
      - lp user [player] permission set tags.use.reeldeal true
      - mamsg [player] &fYou hit &dLevel 25&f in the &dFishing&f job.
      - mamsg [player] &fYou unlocked the &d[ReelDeal]&f tag. &d&l/ᴛᴀɢꜱ
      - discordsrv broadcast **[JOBS]:** __[player]__ has reached **Level 25** in the __Fishing__ job. `/ᴊᴏʙꜱ`
      - broadcast &8[&3&l•&8] &b&lᴊᴏʙꜱ &8→ &b[player]&f has reached &dLevel 25&f in &dFishing&f.
      levelFrom: 25
      levelUntil: 25 
    anglertag:
      command:
      - lp user [player] permission set tags.use.angler true
      - mamsg [player] &fYou hit &dLevel 50&f in the &dFishing&f job.
      - mamsg [player] &fYou unlocked the &d[Angler]&f tag. &d&l/ᴛᴀɢꜱ
      - discordsrv broadcast **[JOBS]:** __[player]__ has reached **Level 50** in the __Fishing__ job. `/ᴊᴏʙꜱ`
      - broadcast &8[&3&l•&8] &b&lᴊᴏʙꜱ &8→ &b[player]&f has reached &dLevel 50&f in &dFishing&f.
      levelFrom: 50
      levelUntil: 50     
  Gui:
    Item: fishing_rod
  Fish:
    cod:
      income: 15.0
      points: 15.0
      experience: 15.0
    salmon:
      income: 20.0
      points: 20.0
      experience: 25.0
    tropical_fish:
      income: 25.0
      points: 25.0
      experience: 25.0
    pufferfish:
      income: 25.0
      points: 25.0
      experience: 25.0
  Kill:
    Player:
      income: 7.5
      points: 7.5
      experience: 7.5
```

---

**Jobs version:** Jobs5.2.3.0.jar

**Server Type (Spigot/Paper/etc):** Paper

**Server Version (using `/ver`):**  Paper version git-Paper-496 (MC: 1.20.4) (Implementing API version 1.20.4-R0.1-SNAPSHOT) (Git: 7ac24a1 on ver/1.20.4)

**Relevant plugins (Delete if this isn't needed):** The only plugin I think that can really mess with this, is pyro, but both plugins ive seen work on other servers together,

**Comment by ClickErrorxD** [comment] 2024-05-16 15:45
https://medal.tv/games/minecraft/clips/2dlesbmFxDKObw/d1337TUmTWnf?invite=cr-MSx3c3QsMjY3NzA3OTcs
![imagexd](https://github.com/Zrips/Jobs/assets/87890013/a45c96f4-5bd7-4fa0-b015-e20a416ce6a4)

**Comment by ClickErrorxD** [comment] 2024-05-23 18:21
I deleted the fisherman file, re-installed it as "Fisher". Still, I am not gaining progression in the job. 
https://medal.tv/games/minecraft/clips/2eQKEenx5R01JN/d133784H37HH?invite=cr-MSxpRHosMjY3NzA3OTcs

**Comment by WhatsTheBadNews** [comment] 2024-05-29 07:24
Also having this issue, seems newest version of Jobs + Pyro results in fishing job not working at all.

**Comment by mrfloris** [comment] 2024-06-06 20:01
I hope this pyrofishing PR gets rolled back.

**Comment by CloudeLecaw** [comment] 2024-06-06 21:27
have you tried if it works without pyrofishing?
Well might be this can also be solved from the pyrofishing site?

**Comment by PyroTempus** [comment] 2024-06-09 10:13
> have you tried if it works without pyrofishing? Well might be this can also be solved from the pyrofishing site?

This isn't on my side - the update broke compatability - as it was working just fine previously.

**Comment by PyroTempus** [comment] 2024-06-09 10:30
> > > have you tried if it works without pyrofishing? Well might be this can also be solved from the pyrofishing site?
> > 
> > 
> > This isn't on my side - the update broke compatability - as it was working just fine previously.
> 
> and if an paper updates breaks the plugin its up to paper to make it work aggain i see.
> 
> Its was not a "who its up to question"
> 
> Sometimes for dev of 3rd plugin its simple to add support aggain. specially when the other site seems to do nothing, So dont let hang down your PyroFishing users ;) Take a look in it, mights its a simple update for you, if not might its still work to add compatibliy aggain.?

Nothing I did broke compatability - and I'm not changing the way my plugin works after 7 years. I didn't add support, jobs did - so it's on their side to do it. 

You can "fix" it by using an older version of jobs before the PR was merged.

**Comment by CloudeLecaw** [comment] 2024-06-09 10:36
jobs never added Pyrofishing support :-D

The users of y

> > > > have you tried if it works without pyrofishing? Well might be this can also be solved from the pyrofishing site?
> > > 
> > > 
> > > This isn't on my side - the update broke compatability - as it was working just fine previously.
> > 
> > 
> > and if an paper updates breaks the plugin its up to paper to make it work aggain i see.
> > Its was not a "who its up to question"
> > Sometimes for dev of 3rd plugin its simple to add support aggain. specially when the other site seems to do nothing, So dont let hang down your PyroFishing users ;) Take a look in it, mights its a simple update for you, if not might its still work to add compatibliy aggain.?
> 
> Nothing I did broke compatability - and I'm not changing the way my plugin works after 7 years. I didn't add support, jobs did - so it's on their side to do it.
> 
> You can "fix" it by using an older version of jobs before the PR was merged.

I see you accepted the user living with the bug just becaus was lucky working for 7 years.

Jobs never added official PyroFishing Support.

Users just where may having luck both worked until to gether,

Using older Version never is a solution in no case. this worsed idea. whats next? Dont update your server if you dont want a this bug?

But i see your not even taking an eye on it, ok fine.

What a luck i am not using Pyro Fishing. And since im knowing about this bug now i will recomment the other servers on removing it when wanne using jobs :)

Its finished here for me.

Have a nice dam and may an update or pr fix come one day <3

**Comment by PyroTempus** [comment] 2024-06-09 10:42
> > > > > have you tried if it works without pyrofishing? Well might be this can also be solved from the pyrofishing site?
> > > > 
> > > > 
> > > > This isn't on my side - the update broke compatability - as it was working just fine previously.
> > > 
> > > 
> > > and if an paper updates breaks the plugin its up to paper to make it work aggain i see.
> > > Its was not a "who its up to question"
> > > Sometimes for dev of 3rd plugin its simple to add support aggain. specially when the other site seems to do nothing, So dont let hang down your PyroFishing users ;) Take a look in it, mights its a simple update for you, if not might its still work to add compatibliy aggain.?
> > 
> > 
> > Nothing I did broke compatability - and I'm not changing the way my plugin works after 7 years. I didn't add support, jobs did - so it's on their side to do it.
> > You can "fix" it by using an older version of jobs before the PR was merged.
> 
> I see you accepted the user living with the bug just becaus was lucky working for 7 years.
> 
> Jobs never added official PyroFishing Support.
> 
> Users just where may having luck both worked until to gether,
> 
> Using older Version never is a solution in no case. this worsed idea. whats next? Dont update your server if you dont want a this bug?
> 
> But i see your not even taking an eye on it, ok fine.
> 
> What a luck i am not using Pyro Fishing. And since im knowing about this bug now i will recomment the other servers on removing it when wanne using jobs :)
> 
> Its finished here for me.
> 
> Have a nice dam and may an update or pr fix come one day <3

LMAO. My god people are seriously wetwipes in here. 

"Jobs never added official PyroFishing support" - (Added compatibility with PyroFishingPro (flo0s)) - Quoted from the Spigot page. 

I will never understand the mentality of some people that run servers. 

If I added support myself, then I would look into fixing it - but this is **completely** out of my control, nor is it my responisibilty to ensure someone elses code and plugin is working to **support** my plugin. 

I'm glad you're not using my resources if you act like this.

**Comment by CloudeLecaw** [comment] 2024-06-09 10:46
> And for zrips, or the guy who made the PR originally - feel free to contact me if you need help investigating this. (please don't include the wetwipe above though).

The first and only good line of this dev today xD

So lets hang in with some popcorn ^^

**Comment by PyroTempus** [comment] 2024-06-09 10:47
> > And for zrips, or the guy who made the PR originally - feel free to contact me if you need help investigating this. (please don't include the wetwipe above though).
> 
> The first and only good line of this dev today xD
> 
> So lets hang in with some popcorn ^^

I asked you to contribute something useful to the conversation, not another pointless comment. Please leave if you have nothing useful to add.

**Comment by CloudeLecaw** [comment] 2024-06-09 10:50
The Patchlog also wrote
`Initial support for 1.20.5+ servers. Don't forget to update CMILib and it will be required for it to work`
What you think people with 1.20.6 servers will do for the moment when it comes to the
decission

Well have a nice sunday

**Comment by mrfloris** [comment] 2024-06-09 11:13
PyroFishingPro and Jobs worked fine together.

This update was a pull request merged to support PyroFishingPro's custom catches.

It's not working out - I hope @Zrips can remove this PR again or patch things so everything's as expected. 

This has nothing to do with 1.20.6 support as far as I can tell. The code from that PR doesn't indicate that. This affects 1.20.4 etc as well.

**Comment by CloudeLecaw** [comment] 2024-06-09 11:13
> Also having this issue, seems newest version of Jobs + Pyro results in fishing job not working at all.

have you tried if it works without pyrofishing?
Well might be this can also be solved from the pyrofishing site? or might the pr can be rolled back?
Who knows at least for the moments is not possible with the version that added 1.20.5/6 support to revert back

**Comment by PyroTempus** [comment] 2024-06-09 11:15
> > Also having this issue, seems newest version of Jobs + Pyro results in fishing job not working at all.
> 
> have you tried if it works without pyrofishing? Well might be this can also be solved from the pyrofishing site? or might the pr can be rolled back? Who knows at least for the moments is not possible with the version that added 1.20.5/6 support to revert back

It works without pyrofishing installed yes. It's after the PR adding support was merged in and released.

**Comment by mrfloris** [comment] 2024-06-09 11:17
> > Also having this issue, seems newest version of Jobs + Pyro results in fishing job not working at all.
> 
> have you tried if it works without pyrofishing? so that we can conclude its from that pr that was made for pyrofishing and no Jobs Issues in case under an other plugins or may unwanted setting?
> 
> Well might the Pyrofishing developer can also give some ideas here how this can be sloved or how it can be reworked to have realy PyroFish copatibilty ...at least the must a reason why this rp was added.. even if it doesnt work like asumed.
> 
> Who knows at least for the moments is that last update added innital 1.20.5/6 support that patchlog said this and people that where using 1.20.5/6 will use this version at the moment.

This is clearly caused by the PR, yes. I've informed zrips about that within 24 hours via DM. This ticket is now open, he's aware it exists. It's a matter of free time to deal with this.

**Comment by CloudeLecaw** [comment] 2024-06-09 11:19
> > > Also having this issue, seems newest version of Jobs + Pyro results in fishing job not working at all.
> > 
> > 
> > have you tried if it works without pyrofishing? Well might be this can also be solved from the pyrofishing site? or might the pr can be rolled back? Who knows at least for the moments is not possible with the version that added 1.20.5/6 support to revert back
> 
> It works without pyrofishing installed yes. It's after the PR adding support was merged in and released.

The the added PyroFishing supported that was added with this update should be fixed or removed within next update.
Lets see. may a fix i the better reason. may noone knows why PyroFishing triggers Jobs like this?
May you know whats causing this behave? Do both plugins watch the same events?
in that case it might be not possible to add the compatibilty like it was wanted in last update with that rp

**Comment by mrfloris** [comment] 2024-06-09 11:22
Pyro has said all he can say, Zrips can reach out if needed. At this point you're just egging on, sorry cloude. Again, when zrips has time he can look into this. No need to start going in circles.

**Comment by Zrips** [comment] 2024-06-10 09:18
1708d3b0a2c8714db4773f60b79b6a9f23478725

**Closed by Zrips** 2024-06-10 09:18 UTC
Labels: Bug Report

**Comment by mrfloris** [comment] 2024-06-10 19:56
This does indeed give exp again, in /jobs stats, but money seems to not be paid out. cmi balance before, catch 5 fish, wait a minute, /cmi balance, no update.

**Comment by mrfloris** [comment] 2024-06-12 12:14
This is what i use successfully on jobs .1
```yaml
  # Catching CUSTOM fish of the PyroFishingPro plugin
  PyroFishingPro:
    CustomTier:
      income: 5.0
      points: 5.0
      experience: 7.0
    Bronze:
      income: 5.0
      points: 5.0
      experience: 7.0
    Gold:
      income: 5.0
      points: 5.0
      experience: 7.0
    Silver:
      income: 5.0
      points: 5.0
      experience: 7.0
    Diamond:
      income: 5.0
      points: 5.0
      experience: 7.0
    Platinum:
      income: 5.0
      points: 5.0
      experience: 7.0
    Mythical:
      income: 5.0
      points: 5.0
      experience: 7.0
      ```
