### ISSUE TITLE
Three out of seven actions in a job don't bring money.

### ISSUE THREAD

**Issue by SuperWife87** [Zrips/Jobs#1824] opened 2024-09-22 17:32 UTC
I have a problem with players not getting paid for all actions in a job. (not OP's either)
We have a single job that should have many actions. Currently, that job has tame, breed, shear, break, place, fish and kill. Unfortunately, no other actions work, more than place, breed, milk and fish.
I have checked that I have updated CMILib and have the latest version of Jobs.
Also checked that all players have jobs.use and jobs.world.worldname.
Checked id and can't find errors in yaml-sites.
(deleted a few jobs quest further down to narrow down config-file)

---

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
Knegare:
  # full name of the job (displayed when browsing a job, used when joining and leaving
  # also can be used as a prefix for the user's name if the option is enabled.
  # Shown as a prefix only when the user has 1 job.

  # NOTE: Must be 1 word
  fullname: Knegare
  # Jobs display name used only for visualization in specific parts. Can contain spaces and color codes
  displayName: '&f☆ ----- {#d9144f}KNEGARE&f ----- ☆'
  # Shortened version of the name of the job. Used as a prefix when the user has more than 1 job.
  shortname: K
  description: Tjäna pengar på mycket!
  # Full description of job to be shown in job browse command
  FullDescription:
  - '&5 Har du aldrig tänkt på att det finns folk'
  - '&5 som inte är rövare och som lever ändå?'
  - ''
  - ' &f Vi har samlat ihop fler jobb'
  - ' &f i ett och samma knegargöra.'
  - ' &f Kika mer under:'
  - '  &5 /jobs info knegare'
  # The colour of the name, for a full list of supported colours, go to the message config. Hex color codes are supported as of 1.16 minecraft version. Example: {#6600cc} or {#Brown}
  ChatColour: #d9144f
  # [OPTIONAL] The colour of the boss bar: GREEN, BLUE, RED, WHITE, YELLOW, PINK, PURPLE.
  BossBarColour: WHITE
  # Option to let you choose what kind of prefix this job adds to your name.
  # Options are: 
  # none - Nothing
  # full - Full title and job name
  # job - Full job name
  # title - Full title
  # shortfull - Short title and job name
  # shortjob - Short job name
  # shorttitle - Short title
  # shorttitlejob - Short title and full job name
  # titleshortjob - Full title and short job name
  chat-display: full
  # [OPTIONAL] - the maximum level of this class
  max-level: 200
  # [OPTIONAL] - the maximum level of this class with specific permission
  # use jobs.[jobsname].vipmaxlevel, in this case it will be jobs.exampleJob.vipmaxlevel
  vip-max-level: 20
  # [OPTIONAL] - the maximum number of users on the server that can have this job at any one time (includes offline players).
  slots: 1000
  # [OPTIONAL] Soft limits will allow to stop income/exp/point payment increase at some particular level but allow further general leveling.
  # In example if player is level 70, he will get paid as he would be at level 50, exp gain will be as he would be at lvl 40 and point gain will be as at level 60
  # This only applies after players level is higher than provided particular limit.
  softIncomeLimit: 50
  softExpLimit: 40
  softPointsLimit: 60
  # Equation used for calculating how much experience is needed to go to the next level.
  # Available parameters:
  #   numjobs - the number of jobs the player has
  #   maxjobs - the number of jobs the player have max
  #   joblevel - the level the player has attained in the job.
  #  NOTE: Please take care of the brackets when modifying this equation.
  leveling-progression-equation: 10*(joblevel)+(joblevel*joblevel*4)
  # Equation used for calculating how much income is given per action for the job level.
  # Available parameters:
  #   numjobs - the number of jobs the player has
  #   maxjobs - the number of jobs the player have max
  #   baseincome - the income for the action at level 1 (as set in the configuration).
  #   joblevel - the level the player has attained in the job.
  # NOTE: Please take care of the brackets when modifying this equation.
  income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(baseincome*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  # Equation used for calculating how much points is given per action for the job level.
  # Available parameters:
  #   numjobs - the number of jobs the player has
  #   maxjobs - the number of jobs the player have max
  #   basepoints - the points for the action at level 1 (as set in the configuration).
  #   joblevel - the level the player has attained in the job.
  # NOTE: Please take care of the brackets when modifying this equation.
  points-progression-equation: basepoints+(basepoints*(joblevel-1)*0.01)-((basepoints+(basepoints*(joblevel-1)*0.01))
    * ((numjobs-1)*0.05))
  # Equation used for calculating how much experience is given per action for the job level.
  # Available parameters:
  #   numjobs - the number of jobs the player has
  #   maxjobs - the number of jobs the player have max
  #   baseexperience - the experience for the action at level 1 (as set in the configuration).
  #   joblevel - the level the player has attained in the job.
  # NOTE: Please take care of the brackets when modifying this equation.
  experience-progression-equation: baseexperience-(baseexperience*((numjobs-1) *0.01))
  # Defines how often in seconds player can rejoin this job. Can be bypassed with jobs.rejoinbypass
  rejoinCooldown: 10
  # GUI icon information when using GUI function
  Gui:
    # You can use the custom player head:
    # Item: player_head
    #   CustomSkull: Notch

    # Name of the material
    ItemStack: AMETHYST_BLOCK
    # Slot number to show the item in the specified row
    slot: 20
    # Enchants of the item
    Enchantments:
    - DURABILITY:1
  # Defines maximum amount of daily quests player can have from THIS job
  # This will not have effect on overall quest amount player will have
  maxDailyQuests: 4
  # Daily quests
  # Each job can have as many daily quests as you want
  # Players will have access to quests from jobs he is currently working at
  Quests:
    # Quest identification. Can be any ONE word or number or both of them. This doesn't have any real meaning but it can't repeat.
    first:
      # Quest name used for quests list, don't forget to enclose it with " "
      Name: Break Oak wood
      # This should be in a format as [actionType];[actionTarget];[amount]
      # [actionType] can be any valid job action. Look lower for all possible action types
      # [actionTarget] can be material name, block type, entity name and so on. This is defined in same way as any generic payable job action
      # [amount] is how many times player should perform this action to complete quest
      Objectives:
      - Break;oak_log;300
      - Place;stone,cobblestone;5
      # Command list to be performed after quest is finished.
      # Use [playerName] to insert players name who finished that quest
      RewardCommands:
      - eco give [playerName] 500
      - msg [playerName] Completed quest!
      # Quest description to be used to explain quest requirements or rewards for player
      RewardDesc:
      - Break 300 Oak wood
      - Get 500 bucks for this
      # Restricted areas where player cant progress his quest
      RestrictedAreas:
      - Arenas
      - myarena
      # Defines chance in getting this quest.
      # If you have set 10 quests and player can have only 2, then quests with biggest chance will be picked most likely
      # This will allow to have some rare quests with legendary rewards
      Chance: 40
      # Defines from which level you want to give option to get this quest
      # You can use both limitations to have limited quests for particular job level ranges
      fromLevel: 1
      # Defines to which job level you want to give out this quest.
      # Keep in mind that player will keep quest even if he is over level limit if he got new one while being under
      # In example: player with level 2 takes quests and levels up to level 5, he still can finish this quest and after next quest reset (check general config file)
      # he will no longer have option to get this quest
      toLevel: 200
    '2':
      Name: "Hugg Ekstam"
      Objectives:
      - "Break;oak_log;100"
      RewardCommands:
      - "money give [playerName] 500"
      - "actionbarmsg [playerName] &5Vildvittran ┃ Daglön intjänad! &f500:-"
      RewardDesc:
      - "&5Hugg Ekstam."
      - "&fBelöning: 500:-"
      - "&2&m-----"
  Tame:
    Wolf:
      income: 5.0
      points: 5.0
      experience: 5.0
    Horse:
      income: 5.0
      points: 5.0
      experience: 5.0
    Parrot:
      income: 5.0
      points: 5.0
      experience: 5.0
    Ocelot:
      income: 5.0
      points: 5.0
      experience: 5.0
    Llama:
      income: 5.0
      points: 5.0
      experience: 5.0
  Breed:
    Horse:
      income: 4.0
      points: 4.0
      experience: 5.0
    Sheep:
      income: 4.0
      points: 4.0
      experience: 5.0
    Cow:
      income: 4.0
      points: 4.0
      experience: 5.0
    mushroom_cow:
      income: 4.0
      points: 4.0
      experience: 5.0
    Pig:
      income: 4.0
      points: 4.0
      experience: 5.0
    Chicken:
      income: 4.0
      points: 4.0
      experience: 5.0
    Wolf:
      income: 4.0
      points: 4.0
      experience: 5.0
    Ocelot:
      income: 4.0
      points: 4.0
      experience: 5.0
    Rabbit:
      income: 4.0
      points: 4.0
      experience: 5.0
    Llama:
      income: 4.0
      points: 4.0
      experience: 5.0
    Turtle:
      income: 4.0
      points: 4.0
      experience: 5.0
  Shear:
    Red:
      income: 4.0
      points: 4.0
      experience: 5.0
    Orange:
      income: 4.0
      points: 4.0
      experience: 5.0
    Yellow:
      income: 4.0
      points: 4.0
      experience: 5.0
    Green:
      income: 4.0
      points: 4.0
      experience: 5.0
    Blue:
      income: 4.0
      points: 4.0
      experience: 5.0
    Light_Blue:
      income: 4.0
      points: 4.0
      experience: 5.0
    Magenta:
      income: 4.0
      points: 4.0
      experience: 5.0
    Pink:
      income: 4.0
      points: 4.0
      experience: 5.0
    White:
      income: 4.0
      points: 4.0
      experience: 5.0
    Light_Gray:
      income: 4.0
      points: 4.0
      experience: 5.0
    Black:
      income: 4.0
      points: 4.0
      experience: 5.0
    Brown:
      income: 4.0
      points: 4.0
      experience: 5.0
    Purple:
      income: 4.0
      points: 4.0
      experience: 5.0
    Cyan:
      income: 4.0
      points: 4.0
      experience: 5.0
    Gray:
      income: 4.0
      points: 4.0
      experience: 5.0
    Lime:
      income: 4.0
      points: 4.0
      experience: 5.0
    mushroom_cow:
      income: 4.0
      points: 4.0
      experience: 5.0 
  Milk:
    Cow:
      income: 5.0
      points: 5.0
      experience: 5.0
  Break:
    red_sand:
      income: 1
      points: 1
      experience: 1
    coarse_dirt:
      income: 1
      points: 1
      experience: 1
    dirt:
      income: 0.25
      points: 0.25
      experience: 0.25
    grass_block:
      income: 0.3
      points: 0.3
      experience: 0.3
    gravel:
      income: 1
      points: 1
      experience: 1.0
    sand:
      income: 0.4
      points: 0.4
      experience: 0.5
    clay:
      income: 1
      points: 1
      experience: 1.0
    chorus_plant:
      income: 1.5
      points: 1.5
      experience: 3.0
    chorus_flower:
      income: 1.5
      points: 1.5
      experience: 3.0
    beetroots-3:
      income: 1.5
      points: 1.5
      experience: 3.0
    wheat-7:
      income: 1.5
      points: 1.5
      experience: 3.0
    carrots-7:
      income: 1.0
      points: 1.0
      experience: 1.0
    potatoes-7:
      income: 1.0
      points: 1.0
      experience: 1.0
    pumpkin:
      income: 0.5
      points: 0.5
      experience: 1.0
    melon:
      income: 0.5
      points: 0.5
      experience: 1.0
    sugar_cane:
      income: 0.2
      points: 0.2
      experience: 0.2
    cocoa-2:
      income: 4
      points: 4
      experience: 4.0
    lily_pad:
      income: 2
      points: 2
      experience: 2.0
    dandelion:
      income: 2
      points: 2
      experience: 2.0
    poppy:
      income: 2
      points: 2
      experience: 2.0
    blue_orchid:
      income: 2
      points: 2
      experience: 2.0
    allium:
      income: 2
      points: 2
      experience: 2.0
    azure_bluet:
      income: 2
      points: 2
      experience: 2.0
    red_tulip:
      income: 2
      points: 2
      experience: 2.0
    orange_tulip:
      income: 2
      points: 2
      experience: 2.0
    white_tulip:
      income: 2
      points: 2
      experience: 2.0
    pink_tulip:
      income: 2
      points: 2
      experience: 2.0
    oxeye_daisy:
      income: 2
      points: 2
      experience: 2.0
    brown_mushroom:
      income: 1
      points: 1
      experience: 1.0
    red_mushroom:
      income: 1
      points: 1
      experience: 1.0
    vine:
      income: 1
      points: 1
      experience: 1.0
    cactus:
      income: 1
      points: 1
      experience: 1.0
    nether_wart:
      income: 1
      points: 1
      experience: 1.0
    andesite:
      income: 1
      points: 1
      experience: 1
    stone:
      income: 1
      points: 1
      experience: 1
    deepslate:
      income: 1.25
      points: 1.25
      experience: 1.25
    granite:
      income: 1
      points: 1
      experience: 1
    diorite:
      income: 1
      points: 1
      experience: 1
    sandstone:
      income: 0.15
      points: 0.15
      experience: 0.2
    chiseled_sandstone:
      income: 0.15
      points: 0.15
      experience: 0.2
    cut_sandstone:
      income: 0.15
      points: 0.15
      experience: 0.2
    coal_ore:
      income: 3
      points: 2
      experience: 2
    deepslate_coal_ore:
      income: 4
      points: 3
      experience: 3
    redstone_ore:
      income: 2.5
      points: 2
      experience: 2
    deepslate_redstone_ore:
      income: 3.5
      points: 3
      experience: 3
    copper_ore:
      income: 3.5
      points: 3
      experience: 2
    deepslate_copper_ore:
      income: 4.5
      points: 4
      experience: 3
    iron_ore:
      income: 3.5
      points: 3
      experience: 2
    deepslate_iron_ore:
      income: 4.5
      points: 4
      experience: 3
    gold_ore:
      income: 5
      points: 4
      experience: 2
    deepslate_gold_ore:
      income: 6
      points: 5
      experience: 3
    lapis_ore:
      income: 7.5
      points: 6
      experience: 2
    deepslate_lapis_ore:
      income: 8.5
      points: 7
      experience: 3
    diamond_ore:
      income: 10
      points: 10
      experience: 10
    deepslate_diamond_ore:
      income: 12.5
      points: 12.5
      experience: 12.5
    emerald_ore:
      income: 15
      points: 15
      experience: 30
    deepslate_emerald_ore:
      income: 17.5
      points: 17.5
      experience: 35
    nether_quartz_ore:
      income: 2.5
      points: 2.5
      experience: 2.5
    obsidian:
      income: 5
      points: 5
      experience: 5
    cobblestone_wall:
      income: 2.5
      points: 2.5
      experience: 2.5
    mossy_cobblestone_wall:
      income: 2.5
      points: 2.5
      experience: 2.5
    nether_bricks:
      income: 1.0
      points: 1
      experience: 1.0
    nether_brick_stairs:
      income: 3
      points: 3
      experience: 3
    nether_brick_fence:
      income: 1
      points: 1
      experience: 1
    netherrack:
      income: 0.1
      points: 0.1
      experience: 0.1
    prismarine:
      income: 2.5
      points: 2.5
      experience: 2.5
    prismarine_bricks:
      income: 2.5
      points: 2.5
      experience: 2.5
    dark_prismarine:
      income: 2.5
      points: 2.5
      experience: 2.5
  Place:
    wheat:
      income: 1
      points: 1
      experience: 1
    potatoes:
      income: 1
      points: 1
      experience: 1
    carrots:
      income: 1
      points: 1
      experience: 1
    beetroots:
      income: 1
      points: 1
      experience: 1
    cocoa:
      income: 1
      points: 1
      experience: 1
    sugar_cane:
      income: 0.01
      points: 0.01
      experience: 0.01
    pumpkin_stem:
      income: 1
      points: 1
      experience: 1
    melon_stem:
      income: 1
      points: 1
      experience: 1
  Fish:
    cod:
      income: 15.0
      points: 15.0
      experience: 15.0
    salmon:
      income: 20.0
      points: 20.0
      experience: 25.0
    tropical_fish:
      income: 25.0
      points: 25.0
      experience: 25.0
    pufferfish:
      income: 25.0
      points: 25.0
      experience: 25.0
  Kill:
    Chicken:
      income: 5.0
      points: 5
      experience: 5.0
    Cow:
      income: 6.0
      points: 5
      experience: 5.0
    Pig:
      income: 5.0
      points: 5
      experience: 5.0
    Sheep:
      income: 5.0
      points: 5
      experience: 5.0
    Wolf:
      income: 10.0
      points: 10
      experience: 5.0
    Creeper:
      income: 15.0
      points: 15
      experience: 15.0
    Skeleton:
      income: 10.0
      points: 10
      experience: 15.0
    Spider:
      income: 10.0
      points: 10
      experience: 15.0
    Zombie:
      income: 10.0
      points: 10
      experience: 15.0
    BLAZE:
      income: 20.0
      points: 20
      experience: 15.0
    CAVE_SPIDER:
      income: 20.0
      points: 20
      experience: 15.0
    ENDERMAN:
      income: 2.0
      points: 2
      experience: 2.0
    GHAST:
      income: 30.0
      points: 30
      experience: 30.0
    GIANT:
      income: 250.0
      points: 250
      experience: 100.0
    IRON_GOLEM:
      income: 30.0
      points: 30
      experience: 30.0
    mushroom_cow:
      income: 5.0
      points: 5
      experience: 5.0
    SILVERFISH:
      income: 3.0
      points: 3
      experience: 5.0
    SNOWMAN:
      income: 2.0
      points: 2
      experience: 4.0
    SQUID:
      income: 2.0
      points: 2
      experience: 2.0
    RABBIT:
      income: 2.0
      points: 2
      experience: 2.0
    GUARDIAN:
      income: 2.0
      points: 2
      experience: 2.0
    SHULKER:
      income: 5.0
      points: 5
      experience: 5.0
    PHANTOM:
      income: 5.0
      points: 5
      experience: 5.0
    DROWNED:
      income: 5.0
      points: 5
      experience: 5.0
    HUSK:
      income: 5.0
      points: 5
      experience: 5.0
    WITHER:
      income: 50.0
      points: 50
      experience: 120.0
    ENDER_DRAGON:
      income: 2000.0
      points: 2000
      experience: 2000.0
    Player:
      income: 7.5
      points: 7
      experience: 7.5
```

---

**Jobs version: 5.2.4.2** 

**Server Type (Spigot/Paper/etc): Paper** 

**Server Version (using `/ver`): 1.21** 

**Relevant plugins (Delete if this isn't needed): CMI (v.9.7.6.3), CMILib (v,1.5.1.4) Jobs, PermissionsEx, Vault**

**Comment by Zrips** [comment] 2024-09-28 08:29
Tested your config file and Tame, Shear, Break worked just fine without any issues, tested with OP and regular player. Issue could be caused by some misconfiguration in general as your job file looks to be correct. Try testing your job on a clean server setup with default jobs config files. 
Closing ticket for now as it looks to be more or a setup issue than actual bug.

**Closed by Zrips** 2024-09-28 08:29 UTC
Labels: Bug Report
