### ISSUE TITLE
Problems with Indentations

### ISSUE THREAD

**Issue by UnioDex** [Zrips/Jobs#532] opened 2019-09-14 11:52 UTC
I opened project in my IDE but it seems really bad. Some indentations made with tab and some of them made with spaces. So indentations looks wrong with Intellij IDEA.

Is there a specific reason for that indentation or can I change it with full spaces (or full tabs, your choice) with a PR?

For example ItemBoostManager.java line 53:
https://i.imgur.com/scheRb1.gif

Some other bad indentation examples:
https://prnt.sc/p60ywb
https://prnt.sc/p60z0p

**Comment by montlikadani** [comment] 2019-09-14 11:54
This is not a bug in the program, but the default GitHub editor that overwrites tabs with space, so it's not perfect.

**Comment by UnioDex** [comment] 2019-09-14 11:55
Well spaces is kinda industry standart now. So turning entire project to spaces will fix all these problems and will look good on every platform.

**Comment by montlikadani** [comment] 2019-09-14 11:59
The GitHub editor has an option called Indent Size, so you can set the tab sizes to be, for example, an if loop, so this overwrites the tabs in the original project.
![kép](https://user-images.githubusercontent.com/30026208/64907817-c3196b80-d6f7-11e9-9210-f3f0c5b37333.png)

Also, closing this, because it can be fixed in the project.

**Closed by montlikadani** 2019-09-14 11:59 UTC
