### ISSUE TITLE
Spam in console

### ISSUE THREAD

**Issue by WIBOR2002222** [Zrips/Jobs#866] opened 2020-07-31 15:55 UTC
Do you know this bug ? 

https://ibb.co/FgygJTM

**Comment by montlikadani** [comment] 2020-07-31 15:57
More info? Which jobs version you using?

**Comment by WIBOR2002222** [comment] 2020-07-31 16:51
The last version of jobs (Jobs4.16.0)
And we use paper 1.16.1

**Comment by montlikadani** [comment] 2020-08-10 17:32
This issue currently can't reproduce. Issue closing until there is a new release of Jobs. If you still have issues with the new release, please make a new ticket.

**Closed by montlikadani** 2020-08-10 17:32 UTC
Labels: Bug Report
