### ISSUE TITLE
action for Stripping Logs is "Place" ?

### ISSUE THREAD

**Issue by smmmadden** [Zrips/Jobs#269] opened 2018-10-19 03:21 UTC
**JOBS v4.9.1 - PaperSpigot 1.13.1 Build 366 - Waterfall Build 230**
I've been trying to find the list of actions that can be taken in Jobs (or minecraft in general for all blocks/items) and couldn't locate one for stripped logs in 1.13.1.

According to the below in my Quests section of the config file, players get paid for stripping logs with the right-click on a log when the action is "Place" and the Target is STRIPPED_OAK_LOG.  That doesn't sound right since I'm not placing it, I'm stripping the log to turn it into wood that was already placed.
![image](https://user-images.githubusercontent.com/10309346/47195714-0e31cf80-d32b-11e8-81be-991ddc871b69.png)
Correct Behavior should be as follows:
The action should be: **Strip**
The Target should be: **OAK_LOG**
The result of completing the Quests for Stripping the OAK_LOG will leave STRIPPED_OAK_LOG block(s).  

The player can then choose to have two other actions on the STRIPPED_OAK_LOG for Break or Place if desired.  So I think the logic is incorrect.  I did try with the above, but "Strip" is invalid and "Place" with OAK_LOG using right-click does nothing in terms of payment or quests.  It only strips the log.

**Comment by montlikadani** [comment] 2018-10-19 13:07
Did you try the _Break_ action?
It would be a problem with this _Strip_ action. The problem is that Spigot is not yet fully available for the event to do this event. So such an event, such as StripBlockEvent (or other), is not yet assigned to Spigot, but I still think of Paper.

**Comment by smmmadden** [comment] 2018-10-19 17:47
I tried break but it does nothing other than stripping the wood.  Let's keep this open until we know for sure what the ActionType will be for stripping logs for wood.

**Comment by Zrips** [comment] 2019-01-30 14:06
1d897e9d3e8b15f8221823ade62490f115fc2593

**Closed by Zrips** 2019-01-30 14:06 UTC
Labels: enhancement
