### ISSUE TITLE
jobs reborn isn't recognising sub-type ID

### ISSUE THREAD

**Issue by timmyturnr** [Zrips/Jobs#282] opened 2018-11-05 17:47 UTC
![2018-11-05_11 45 08](https://user-images.githubusercontent.com/44783026/48016112-52c1b700-e0f0-11e8-8328-5af4c649abca.png)

as you can see its just repeating the same id.

jobsconfig is default hasn't been change

**Comment by montlikadani** [comment] 2018-11-05 20:00
Do you use the latest version of JobsReborn?

**Comment by timmyturnr** [comment] 2018-11-05 20:49
yes 4.9.1

**Comment by smmmadden** [comment] 2018-11-05 22:30
is it possible that you have the item listed in the jobConfig.yml under Break?  I've just gone through all mine and don't see any duplicates.  I'm using Waterfall 1.13.2 (build 234) PaperSpigot 1.13.2 (build 418) with Jobs Reborn 4.9.1 (dev build of 11/1/2018). 
What server & versions are you using?  Be as specific as I was, that'll help a lot.
![image](https://user-images.githubusercontent.com/10309346/48030850-59682280-e120-11e8-9414-4f3d7161a3c6.png)

**Comment by timmyturnr** [comment] 2018-11-06 00:45
yeah the items are listed un jobsconfig.yml under build im on voodoo servers running 1.12.2 spigot

**Comment by smmmadden** [comment] 2018-11-06 03:09
okay, but what build of Spigot are you running with.  Saying 1.12.2 doesn't tell us if you are on the first build of 1.12.2 the middle or the last one built today.  You can type in /version to get the version.  It will also tell you if you are behind in builds.  Also if you post configuration content, put it out on hastebin or pastebin where the format is retained.  Often times, one character, space or typo can cause issues.

**Comment by timmyturnr** [comment] 2018-11-06 03:18
This server is running CraftBukkit version git-Spigot-7754231-9a1f5ee (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)

**Comment by montlikadani** [comment] 2018-11-06 14:41
Try resetting the Translatable_words.yml file to the default by moving it somewhere to avoid being in the Translatable_Words folder.

**Comment by montlikadani** [comment] 2018-11-06 14:43
Try resetting the Translatable_words.yml file to the default by moving it somewhere to avoid being in the Translatable_Words folder.

**Comment by timmyturnr** [comment] 2018-11-06 14:45
okay ill give that a try

**Comment by timmyturnr** [comment] 2018-11-06 14:47
that didn't work

**Comment by timmyturnr** [comment] 2018-11-06 14:49
I found the problem in that folder. it said this   
189-BIRCH_FENCE: Birch Fence
  184-BIRCH_FENCE_GATE: Birch Fence Gate
  18-LEAVES: Birch Leaves
  17-LOG: Birch Log
  135-BIRCH_WOOD_STAIRS: Birch Wood Stairs
  425-BANNER: Banner

**Comment by montlikadani** [comment] 2018-11-06 15:00
The problem is that you do not have the latest Translatabe_Words file since we have recently updated it.
You can check the new file: [link](download2269.mediafire.com/p1m3di90efog/hsdfbiokzv5w34o/Words_en.yml)
Compare it and follow it.

**Comment by timmyturnr** [comment] 2018-11-06 15:02
the link says not found

**Comment by montlikadani** [comment] 2018-11-06 15:05
Sry, download2269.mediafire.com/p1m3di90efog/hsdfbiokzv5w34o/Words_en.yml

**Comment by montlikadani** [comment] 2018-11-06 15:06
Sorry, wrong link, http://www.mediafire.com/file/hsdfbiokzv5w34o/Words_en.yml/file

**Comment by timmyturnr** [comment] 2018-11-06 15:08
thanks for everything

**Comment by montlikadani** [comment] 2018-11-06 15:09
Now working?

**Comment by timmyturnr** [comment] 2018-11-06 15:13
okay I added it but no its not working but I know that's what needs to be fixed cause when I manually changed something that worked

**Comment by montlikadani** [comment] 2018-11-06 15:16
Then works or no? Or did you just change something in the configuration and did it work?

**Comment by timmyturnr** [comment] 2018-11-06 15:16
that file when I added it didn't work but when I manually changed it that worked

**Comment by timmyturnr** [comment] 2018-11-06 15:38
I did and it just goes back to the old file?!

**Comment by montlikadani** [comment] 2018-11-06 15:40
You are not using the latest version of Jobs. Download the DEV from here. version: https://github.com/Zrips/Jobs/releases

**Comment by timmyturnr** [comment] 2018-11-06 15:41
I am using that verison though 4.9.1

**Comment by montlikadani** [comment] 2018-11-06 15:44
Does the file look what I've sent, similar to it?

**Comment by timmyturnr** [comment] 2018-11-06 15:47
no its the same old file

**Comment by montlikadani** [comment] 2018-11-06 15:53
**Which one to use with this one?**

The old file this:
![kep](https://user-images.githubusercontent.com/30026208/48075805-49197b80-e1e4-11e8-8188-28df3e3e90b9.png)
The new file this:
![kep](https://user-images.githubusercontent.com/30026208/48075825-50d92000-e1e4-11e8-94af-b97b59117849.png)

**Comment by montlikadani** [comment] 2018-11-06 16:02
I'm not going to increase the version number because what the plugin.yml checks for the server and if there is a version leap, it will notify the operators.

**Comment by smmmadden** [comment] 2018-11-06 16:17
@timmyturnr - according to Spigot the build you are using is older than 9 months.  How many builds are you behind when you did /version ?  I suspect you are behind by several hundred builds??

@montlikadani - I gave two options above.  The best practice is when you create a build that is expected to be downloaded any player, then the version and/or build details should be different to distinguish one build over the next.  As a new developer, this is what's considered a best business practice.

If you are not following this methodology there will be reports like this where we don't know which build of 4.9.1 they are using.  Point in fact is my comment above about how many builds he is.  It is ultimately your choice, but I've been doing this for several decades and providing my experience to help avoid problems downstream.  There are more than the options I provided, just think about how you will support that change. :-)

**Comment by montlikadani** [comment] 2018-11-06 16:36
Yes, I believe, and I see you writing very meaningful texts and having lots of knowledge.
Later I'll figure out what version I've tested, because I'm using this plugin.yml version checker. I know there are more, but I still use it.

**Comment by timmyturnr** [comment] 2018-11-06 16:38
06.11 11:46:07 [Server] WARN java.lang.IllegalArgumentException: The embedded resource 'locale/messages_en.yml' cannot be found in plugins/Jobs.jar
06.11 11:46:07 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.saveResource(JavaPlugin.java:195)
06.11 11:46:07 [Server] WARN at com.gamingmesh.jobs.config.YmlMaker.saveDefaultConfig(YmlMaker.java:94)
06.11 11:46:07 [Server] WARN at com.gamingmesh.jobs.config.LanguageManager.load(LanguageManager.java:102)
06.11 11:46:07 [Server] WARN at com.gamingmesh.jobs.config.GeneralConfigManager.reload(GeneralConfigManager.java:347)
06.11 11:46:07 [Server] WARN at com.gamingmesh.jobs.Jobs.reload(Jobs.java:600)
06.11 11:46:07 [Server] WARN at com.gamingmesh.jobs.Jobs.startup(Jobs.java:533)
06.11 11:46:07 [Server] WARN at com.gamingmesh.jobs.Jobs.onEnable(Jobs.java:808)
06.11 11:46:07 [Server] WARN at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
06.11 11:46:07 [Server] WARN at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
06.11 11:46:07 [Server] WARN at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
06.11 11:46:07 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:384)
06.11 11:46:07 [Server] WARN at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:333)
06.11 11:46:07 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:422)
06.11 11:46:07 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:383)
06.11 11:46:07 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:338)
06.11 11:46:07 [Server] WARN at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272)
06.11 11:46:07 [Server] WARN at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545)
06.11 11:46:07 [Server] WARN at java.lang.Thread.run(Thread.java:748)
06.11 11:46:07 [Server] INFO There was some issues when starting plugin. Please contact dev about this. Plugin will be disabled.

this is what happens when I install that one you sent me

**Comment by montlikadani** [comment] 2018-11-06 16:54
Do you using the [DEV. version](https://github.com/Zrips/Jobs/releases)?

**Comment by timmyturnr** [comment] 2018-11-06 16:56
that's the one you sent me

**Comment by montlikadani** [comment] 2018-11-06 16:59
Try restart or reload the server.

**Comment by timmyturnr** [comment] 2018-11-06 17:00
I have twice now

**Comment by timmyturnr** [comment] 2018-11-06 17:02
can we talk on discord?

**Comment by montlikadani** [comment] 2018-11-06 17:06
Ok, my name: #montlikadani#1641
But I didn't talk, I only writing.

**Comment by timmyturnr** [comment] 2018-11-06 17:08
that didn't work mine is timmyturner#4616

**Comment by xinxcode** [comment] 2018-11-13 19:03
Oh I have same problem

**Comment by montlikadani** [comment] 2019-08-11 13:12
To fix these issues see this instructions to fix some repeated material names: https://github.com/Zrips/Jobs/wiki/Legacy-config-support
Some names are not work correctly, but this is not plugin problem, this is client issue.

**Closed by montlikadani** 2019-08-11 13:12 UTC
Labels: bug, duplicate

**Comment by HunterzTheBoz** [comment] 2021-09-24 19:53
Hallo How to enter gui job reborn on znpcs any know?
