### ISSUE TITLE
CraftItemEvent Error & not receive money for Hunter Jobs.

### ISSUE THREAD

**Issue by clarkkentz** [Zrips/Jobs#419] opened 2019-05-12 17:04 UTC
```
[00:03:05 ERROR]: Could not pass event CraftItemEvent to Jobs v4.11.1
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:501) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:486) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1657) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_201]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_201]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.gamingmesh.jobs.CMILib.ItemManager$1
        at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:3329) ~[?:?]
        at com.gamingmesh.jobs.CMILib.ItemManager$CMIMaterial.isDye(ItemManager.java:3325) ~[?:?]
        at com.gamingmesh.jobs.listeners.JobsPaymentListener.onInventoryCraft(JobsPaymentListener.java:592) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor1178.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300) ~[PaperSpigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-PaperSpigot-"8b18730"]
        ... 16 more
```

**Comment by montlikadani** [comment] 2019-05-12 17:08
Same as #210

**Comment by mrcoffee1026** [comment] 2019-05-13 01:01
The craftItemEvent error may be a duplicate of #210 but the no pay for Hunter Jobs is an issue ... players noticed it in version 4.10.3... I updated to the 4.11.1 (Experimental) in hopes that it was resolved in the later version, but it is still a problem.  No exp or pay for killing of HOSTILE mobs for some reason... Passive mobs are still giving credit... there is a possibility that using a sword instead of a bow still gives credit, but there's no reason in the set up file for different treatment of either the mobs nor the tool used so something isn't right.

**Comment by montlikadani** [comment] 2019-05-13 19:22
This works properly for me without console error. Could you please send a jobConfig.yml file?

**Comment by mrcoffee1026** [comment] 2019-05-13 19:49
jobsConf.yml: https://pastebin.com/9t5p6xY5

**Comment by Zrips** [comment] 2019-05-26 08:13
@mrcoffee1026 
Make sure that you have this one disabled
```
    MonsterDamage:
      # This section controls how much damage player should do to monster for player to get paid
      # This prevents from killing monsters in one hit when they suffer in example fall damage
      Use: false
      Percentage: 60
```
or atleast set to lower numbers if you are killing partially dead monster

**Comment by Zrips** [comment] 2019-05-26 08:23
@clarkkentz 
Any errors while starting the server?

**Comment by clarkkentz** [comment] 2019-05-26 08:24
> @clarkkentz
> Any errors while starting the server?

No errors.

**Comment by mrcoffee1026** [comment] 2019-05-28 00:43
> @mrcoffee1026
> Make sure that you have this one disabled
> 
> ```
>     MonsterDamage:
>       # This section controls how much damage player should do to monster for player to get paid
>       # This prevents from killing monsters in one hit when they suffer in example fall damage
>       Use: false
>       Percentage: 60
> ```
> 
> or atleast set to lower numbers if you are killing partially dead monster

This is the setting I have currently, and - in any case - the monsters we are not being paid for we're taking from full hearts to 0 with our attacks... freshly, naturally spawned mobs in the map at night... not from spawners.

**Comment by montlikadani** [comment] 2020-01-24 16:49
This can't happen anymore in the latest versions.

**Closed by montlikadani** 2020-01-24 16:49 UTC
Labels: bug, duplicate
