### ISSUE TITLE
Wheat and other crops don't properly count towards the Farmer break action

### ISSUE THREAD

**Issue by JustAMatt** [Zrips/Jobs#953] opened 2020-10-10 18:07 UTC
Wheat aged 7 (checked with F3) and other crops age dependant will not properly register with the farmer job. However, crops placed with WorldWdit (//set wheat[age=7] will register. Crops grown with bonemeal will not count towards the job and netither will naturally grown crops. Just those placed with WorldEdit. 

```

**CONFIG SECTION (DELETE IF NOT RELEVANT):**
```
#####################################
#####################################
```

---

**Server Type (Spigot/Paperspigot/etc):** Paper 219

**Server Version (using `/ver`):** 1.16.3

Jobs4.16.2

**Comment by montlikadani** [comment] 2020-10-10 18:10
And what is the issue? Breaking crops/wheat not paying?

**Comment by JustAMatt** [comment] 2020-10-10 18:19
> And what is the issue? Breaking crops/wheat not paying?

No pay, no exp (and if I had them on), no points.

**Comment by montlikadani** [comment] 2020-10-10 18:35
Seems I got paid for breaking wheats. So you set the wheat with WorldEdit first time and you don't get paid for breaking it? Or setting with WE its working?

**Comment by JustAMatt** [comment] 2020-10-10 18:37
> Seems I got paid for breaking wheats. So you set the wheat with WorldEdit first time and you don't get paid for breaking it? Or setting with WE its working?

Setting them with WorldEdit at age 7 will pay. Letting them grow up to age 7 won't work. Did you use a different config?

**Comment by montlikadani** [comment] 2020-10-10 19:38
Send here your generalConfig from Jobs folder

**Comment by JustAMatt** [comment] 2020-10-10 19:47
https://hastebin.com/ididexozip.yaml generalconfig

**Comment by JustAMatt** [comment] 2020-10-12 05:45
Anything wrong with the generalConfig?

**Comment by Zrips** [comment] 2020-10-29 13:36
@JustAMatt By any chance you have some plugin which could control wheat growth? As of testing, i cant reproduce this issue. Fully grown wheat pays as it should without any issues

**Comment by JustAMatt** [comment] 2020-10-30 01:48
I do not have any plugins that control wheat-growth. I've seen other players with the same issue with farmer before in the discord as well. I'll send a link to the plugin list @Zrips

**Comment by Zrips** [comment] 2020-10-30 09:35
@JustAMatt Simplest way to determine if this is an issue with another plugin is to run server with Jobs plugin alone. If issue still persists then another test you could perform is to stop server, rename Jobs folder to something like Jobs_Backup and start server. This will reset all values and you can retest it, if issue is gone then something with configuration causes this issue which would be nice to find out which one exactly. If issue still persists, then something wrong with the code. But as i cant reproduce this issue, then its ether with another plugin or your particular configuration. In any case, at this point you will need to do some testing at your end to find out whats the difference here.

**Comment by montlikadani** [comment] 2020-11-16 17:42
Closing as there are no answer.

**Closed by montlikadani** 2020-11-16 17:42 UTC
Labels: Bug Report, not enough info
