### ISSUE TITLE
Compatibility issue with Plan (Jobs 4.10.3)

### ISSUE THREAD

**Issue by CypherPhyre** [Zrips/Jobs#377] opened 2019-03-01 00:51 UTC
https://pastebin.com/YK1Zg8QK

Plan-4.7.0-SNAPSHOT-b2.jar
Jobs4.10.3.jar

There were no issues with jobs4.10.1

**Comment by montlikadani** [comment] 2019-03-01 14:01
I don't think the software called Plan supports Bukkit plugins. There is no right way for this error in Jobs to fix it.

**Comment by CypherPhyre** [comment] 2019-03-01 14:26
https://www.spigotmc.org/resources/plan-player-analytics.32536/

It IS a Spigot/Bukkit plugin that I have used without issue on my server for the better part of a year. This issue only affects the latest version of Jobs

**Comment by montlikadani** [comment] 2019-03-01 14:30
Ok, but there is no proper path for the Jobs code in this error.

**Comment by CypherPhyre** [comment] 2019-03-01 15:17
That is the full error.
Previous versions of Jobs work with the current version of Plan. This error only shows when using the current version of Jobs.

**Comment by Rsl1122** [comment] 2019-03-02 07:21
I have examined the code and the error is caused by a recent commit that changes how JobsManager is returned by Jobs#getDBManager https://github.com/Zrips/Jobs/blame/master/src/main/java/com/gamingmesh/jobs/Jobs.java#L285

If JobsManager is initialized in the getter, JobsDAO returned by it will be null, leading to this exception.

**Comment by Rsl1122** [comment] 2019-03-18 18:34
Confirmed fixed in 417b6f7

**Comment by montlikadani** [comment] 2019-03-18 18:37
Yea, just a class registering problem was. Did I release a dev version, that you can download and test it?

**Comment by Rsl1122** [comment] 2019-03-18 18:38
I cloned the latest commit from `master` and ran `mvn package` to get the latest version

**Closed** 2019-05-02 13:34 UTC
Labels: bug
