### ISSUE TITLE
0 Workers on All Jobs

### ISSUE THREAD

**Issue by Cerexus** [Zrips/Jobs#748] opened 2020-04-15 10:13 UTC
I use jobs for months now and remembered that no workers are counted for dynamic payment.
Ingame it shows me for every job 0 workers.
I use MySQL.

**Comment by montlikadani** [comment] 2020-04-15 10:17
Send more informations like jobs version (number, not latest), screenshot about the problem.

**Comment by Cerexus** [comment] 2020-04-15 11:32
As i wrote the problem exists for more than one version and a screenshot of the itemgui  which displays 0? I dont think that will help...

Version 4.15.7

**Comment by montlikadani** [comment] 2020-04-15 11:40
The screenshot is for proof, and if there is no image of it, which is an error in the game, this issue will be invalid.

**Comment by Cerexus** [comment] 2020-04-16 04:36
![Screenshot_20200416-062634_ChatCraft](https://user-images.githubusercontent.com/12428603/79415010-79a23f00-7fac-11ea-9908-3f5adcb93aff.jpg)
![Screenshot_20200416-063431_Plesk Mobile](https://user-images.githubusercontent.com/12428603/79415029-84f56a80-7fac-11ea-8c28-a0b79692b1d2.jpg)

**Comment by Cerexus** [comment] 2020-04-16 04:41
![Screenshot_20200416-063732_ChatCraft](https://user-images.githubusercontent.com/12428603/79415301-52983d00-7fad-11ea-866b-8afbd8685684.jpg)

**Comment by montlikadani** [comment] 2020-05-02 13:10
https://github.com/Zrips/Jobs/commit/e1d22533d1178eeca4fc4c9a9a1d49c03d25659f

**Closed by montlikadani** 2020-05-02 13:10 UTC

**Comment by Cerexus** [comment] 2020-05-23 20:27
Hm, i updated the plugin and it still shows 0 workers... I tested it with a fresh mysql db too.

**Comment by Cerexus** [comment] 2020-06-01 21:19
@montlikadani ?

**Comment by montlikadani** [comment] 2020-06-02 05:54
Can't reproduce. This works as it should.

![kép](https://user-images.githubusercontent.com/30026208/83484871-2c1f5a00-a4a6-11ea-9eaf-84c21afec35c.png)

**Comment by Cerexus** [comment] 2020-06-02 06:10
@montlikadani    maybe its the config, could you test it with my conf?
https://pastebin.com/nTvaKsFm

**Comment by montlikadani** [comment] 2020-06-02 06:22
There is no any option in generalConfig that relates to total workers of a job. You can try to disable `MultiServerCompatability` that maybe prevents that. If it not works then you should make a new database (save the current one, delete and regenerate by server restart), and try to join to a job (only you) and see whats the result, if the result still 0, do a reload to your server.

**Comment by Cerexus** [comment] 2020-06-02 06:34
@montlikadani but the multiserver option is needed :/
