### ISSUE TITLE
PlaceHolder Bug

### ISSUE THREAD

**Issue by Pyario** [Zrips/Jobs#442] opened 2019-06-01 14:27 UTC
***Description of issue:**
Placeholder BUG!

Type: Spigot
Version: 1.14.2
JobsVersion: 4.12.0

Screen: http://prntscr.com/nwauym

The Xp points are not displayed correctly or even correctly but with a longer digit number. I do not know if it's on the latest PlaceHolderAPI version or in the query in JobsPluign! :)

Best Regards,

Pyario

**Comment by montlikadani** [comment] 2019-06-01 14:34
This is not a bug, just you have 5.90t2 amount of exp. We does not convert the exp amount to trillion, million or other currency format, we just replacing the placeholder. Just ignore it.

**Comment by Pyario** [comment] 2019-06-01 14:40
Yes, but I do not want to have such a long time in there. because then the whole scoreboard would be too long if I still put the job name? How can I fix this?

**Comment by montlikadani** [comment] 2019-06-01 20:29
So? If you close the Issue, then we can not add this suggestion to plugin as placeholder. Keep open and we try to short the placeholder result.

**Comment by Pyario** [comment] 2019-06-01 21:38
Okay, sorry. I
 opened it again. 
Do you need any other things to fix, or is it understandable?

Best Regards,

Pyario

**Comment by montlikadani** [comment] 2019-06-01 21:39
Possible, just need a long time to try something.

**Comment by montlikadani** [comment] 2019-06-03 14:41
In this commit should fix the number digit issue. If you wanted this, please wait the plugin release.

**Closed by montlikadani** 2019-06-03 14:41 UTC
Labels: enhancement, open to PR
