### ISSUE TITLE
Cant gain money on 4.7.2 + Error

### ISSUE THREAD

**Issue by SoraShiunin** [Zrips/Jobs#214] opened 2018-08-12 22:41 UTC
https://pastebin.com/DbgnqYL0
Simple as that, cant gain money, that error appears sometimes in console (when someone joins?).

**Comment by montlikadani** [comment] 2018-08-13 05:27
This is duplicate of #209 & #210

**Comment by SoraShiunin** [comment] 2018-08-14 12:07
About that 'cant gain money' issue hummmm

**Comment by montlikadani** [comment] 2018-08-14 14:31
Is the official Vault plugin installed?
Did you edit something in this feature?:
``
income-progression-equation: baseincome+(baseincome*(joblevel-1)*0.01)-((baseincome+(joblevel-1)*0.01) * ((numjobs-1)*0.05))
``

**Closed** 2018-10-15 12:55 UTC
Labels: bug, duplicate
